const cacheName = "mapletonassets";
const directories = [ 
"./assets/4w.webp",
"./assets/4w2.webp",
"./assets/4w3.webp",
"./assets/blank.webp",
"./assets/Crate.webp",
"./assets/dark_stuff.webp",
"./assets/dead.webp",
"./assets/dead3.webp",
"./assets/dead_2.webp",
"./assets/door_end_closed.webp",
"./assets/door_end_closed_1.webp",
"./assets/door_end_closed_2.webp",
"./assets/door_end_closed_3.webp",
"./assets/door_end_open.webp",
"./assets/door_end_open_1.webp",
"./assets/door_end_open_2.webp",
"./assets/door_end_open_3.webp",
"./assets/down.webp",
"./assets/east.webp",
"./assets/flashlight_off.webp",
"./assets/flashlight_on.webp",
"./assets/haze1.webp",
"./assets/haze2.webp",
"./assets/haze3.webp",
"./assets/icon.webp",
"./assets/item_end.webp",
"./assets/key_end.webp",
"./assets/key_end_empty.webp",
"./assets/key_item.webp",
"./assets/left.webp",
"./assets/left2.webp",
"./assets/left3.webp",
"./assets/left_arrow.webp",
"./assets/level_loading.webp",
"./assets/level_start.webp",
"./assets/loading.webp",
"./assets/map.webp",
"./assets/north.webp",
"./assets/note1.webp",
"./assets/note2.webp",
"./assets/note3.webp",
"./assets/note_end.webp",
"./assets/note_item.webp",
"./assets/note_tile.webp",
"./assets/option1_tile.webp",
"./assets/option2_tile.webp",
"./assets/panel.webp",
"./assets/pointer.webp",
"./assets/power_door.webp",
"./assets/puzzel_end.webp",
"./assets/right.webp",
"./assets/right2.webp",
"./assets/right3.webp",
"./assets/right_arrow.webp",
"./assets/rust.webp",
"./assets/rustybg.webp",
"./assets/rusty_wall.webp",
"./assets/salt_item.webp",
"./assets/south.webp",
"./assets/star.webp",
"./assets/straight.webp",
"./assets/straight2.webp",
"./assets/straight2_2.webp",
"./assets/straight_2.webp",
"./assets/straight_2_3.webp",
"./assets/straight_3.webp",
"./assets/strobe_1.webp",
"./assets/strobe_2.webp",
"./assets/strobe_3.webp",
"./assets/strobe_4.webp",
"./assets/strobe_5.webp",
"./assets/strobe_6.webp",
"./assets/strobe_7.webp",
"./assets/strobe_8.webp",
"./assets/strobe_item.webp",
"./assets/supply_end.webp",
"./assets/supply_end_open.webp",
"./assets/t.webp",
"./assets/t2.webp",
"./assets/t3.webp",
"./assets/teammate.webp",
"./assets/teammate_fallen.webp",
"./assets/thing.webp",
"./assets/thing0.webp",
"./assets/thing1.webp",
"./assets/thing2.webp",
"./assets/thing3.webp",
"./assets/thing4.webp",
"./assets/thing_1.webp",
"./assets/thing_2.webp",
"./assets/thing_3.webp",
"./assets/thing_4.webp",
"./assets/tleft.webp",
"./assets/tleft2.webp",
"./assets/tleft3.webp",
"./assets/tright.webp",
"./assets/tright2.webp",
"./assets/tright3.webp",
"./assets/up.webp",
"./assets/west.webp",
"./assets/models/4w.bin",
"./assets/models/4w.gltf",
"./assets/models/dead.bin",
"./assets/models/dead.gltf",
"./assets/models/left.bin",
"./assets/models/left.gltf",
"./assets/models/puzzel_end.bin",
"./assets/models/puzzel_end.gltf",
"./assets/models/right.bin",
"./assets/models/right.gltf",
"./assets/models/straight.bin",
"./assets/models/straight.gltf",
"./assets/models/supply_end.bin",
"./assets/models/supply_end.gltf",
"./assets/models/t.bin",
"./assets/models/t.gltf",
"./assets/models/tunnel_3.gltf",
"./assets/models/t_left.bin",
"./assets/models/t_left.gltf",
"./assets/models/t_right.bin",
"./assets/models/t_right.gltf",
 "./assets/models/adam-niescioruk-bWiH0PDTB-g-unsplash.jpg",
 "./assets/models/textures/carpet2.jpg",
 "./assets/models/textures/carpet3.jpg",
 "./assets/models/textures/ciel_office.jpg",
 "./assets/models/textures/ciel_office_1.jpg",
 "./assets/models/textures/ciel_office_3.jpg",
 "./assets/models/textures/Crate_Material_BaseColor.jpg",
 "./assets/models/textures/engin-akyurt-in8CoZMm8io-unsplash.jpg",
 "./assets/models/textures/office wall.jpg",
 "./assets/models/textures/office wall_2.jpg",
 "./assets/models/textures/office wall_3.jpg",
 "./assets/models/textures/puzzel_end.jpg",
 "./assets/models/textures/rust.jpg",
 "./assets/models/textures/takis-politis-FmeJ2pV6YsU-unsplash.jpg",
"./SFX/16955_1461335342.mp3",
"./SFX/18576_1464796417.mp3",
"./SFX/ambient_noise 1.mp3",
"./SFX/ambient_noise 3.mp3",
"./SFX/ambient_noise 4.mp3",
"./SFX/ambient_noise 5.mp3",
"./SFX/ambient_noise 6.mp3",
"./SFX/background_music_1.mp3",
"./SFX/background_music_2.mp3",
"./SFX/background_music_3.mp3",
"./SFX/background_music_4.mp3",
"./SFX/bell_chime.mp3",
"./SFX/close_bin.mp3",
"./SFX/elevator_down.mp3",
"./SFX/gameover.mp3",
"./SFX/item_aquired.mp3",
"./SFX/item_dropped.mp3",
"./SFX/it_is_here.mp3",
"./SFX/license.txt",
"./SFX/man_down 2.mp3",
"./SFX/man_down.mp3",
"./SFX/map_tear.mp3",
"./SFX/player_breath.mp3",
"./SFX/puzzel.mp3",
"./SFX/something coming 1.mp3",
"./SFX/something coming 2.mp3",
"./SFX/something coming 3.mp3",
"./SFX/step.mp3",
"./SFX/step1.mp3",
"./SFX/step2.mp3",
"./SFX/strobe.mp3",
"./SFX/strobeEnd.mp3",
"./SFX/thing.mp3",
"./SFX/thing_breath.mp3",
"./SFX/thing_roar_1.mp3",
"./SFX/thing_roar_2.mp3",
"./SFX/thing_roar_3.mp3",
"./SFX/thing_step_1.mp3",
"./SFX/thing_step_2.mp3"
];


self.addEventListener("install", e=>{
    e.waitUntil((async()=>{
        const cache = await caches.open(cacheName);
        cache.addAll(directories).catch(e=>console.log(e));
    })());
});

self.addEventListener('fetch', e => {
    e.respondWith((async ()=>{
        const r = await caches.match(e.request);
        if(r) return r;
        const res = await fetch(e.request);
        const cache = await caches.open(cacheName);
        cache.put(e.request, res.clone());
        return res;
    })());
});